 name 			= "SPRES (SinglePlayerRESpawn)";                     // Name of your mod
 author 		= "snakebyte" // Affects Arma 3 Launcher, when the mod are loaded as local
 logo 			= "logo_ca_small.paa";                                // Logo displayed in the main menu
 logoOver 		= "logo_ca_small.paa";                                // When the mouse is over, in the main menu
 tooltip 		= "SPRES (SinglePlayerRESpawn)";
 actionName 	= "Github";                                // Button-text
 action 		= "https://github.com/snakebyte85/SPRES"        // Website URL, that can be accessed from the expansions menu
 overview 		= "Single Player Respawn using multiplayer settings and features"; // Supports structured text
 overviewPicture = "logo_ca.paa";
 hideName 		= 0;                                        // Hide the extension name
 hidePicture	= 0;	                                    // Hide the extension menu
 dlcColor[] 	= {0.23,0.39,0.30,1};                       // Color used for DLC stripes and backgrounds (RGBA)
